[package]
name = "Serialize"
version = "0.1.0"
authors = ["marat.tukhbatullin <marat.tukhbatullin@mera.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"